# Generated by Django 6.0.3 on 2026-03-08 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('thesis', '0002_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='thesis_file',
            field=models.FileField(blank=True, null=True, upload_to='thesis_files/'),
        ),
    ]
